name: Deploy OpenLens to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  NODE_VERSION: '18'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for GitHub Pages

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安裝依賴套件
        run: npm ci

      - name: 執行程式碼檢查
        run: npm run lint

      - name: 建置靜態檔案
        run: npm run build

      - name: 上傳建置檔案
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    runs-on: ubuntu-latest
    name: Deploy to GitHub Pages
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: 部署到 GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

  manual-deploy:
    runs-on: ubuntu-latest
    name: Manual Deploy to GitHub Pages
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: 檢出程式碼
        uses: actions/checkout@v4

      - name: 設定 Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: 安裝依賴套件
        run: npm ci

      - name: 建置靜態檔案
        run: npm run build

      - name: 手動部署到 GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
          cname: openlens.xsong.us # 自訂網域

      - name: 輸出部署資訊
        run: |
          echo "手動部署成功！"
          echo "部署網址: https://openlens.xsong.us"
